version: '3.3'
services:
  mongodb_container:
    container_name: database
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db


  backend:
    container_name: backend
    image: backend:latest
    ports:
      - 5000:5000
    depends_on: [mongodb_container]

    
  frontend:
      container_name: frontend
      image: frontend:latest
      ports:
        - 4200:3001
      depends_on: [backend]
      links:
        - backend:backend
volumes:
  mongodb_data_container: